// src/lib/navigation/chrome.svelte
<script lang="ts">
	import Icon from 'svelte-icons-pack/Icon.svelte';
	import VscChromeClose from 'svelte-icons-pack/vsc/VscChromeClose';
	import VscChromeRestore from 'svelte-icons-pack/vsc/VscChromeRestore';
	import VscChromeMinimize from 'svelte-icons-pack/vsc/VscChromeMinimize';
	import VscChromeMaximize from 'svelte-icons-pack/vsc/VscChromeMaximize';
	import { appWindow } from '@tauri-apps/api/window';
	import { useLocation } from 'svelte-navigator';

	const currentLocation = useLocation();

	async function windowIsMaximized() {
		return await appWindow.isMaximized();
	}

	// Get initial value
	let isMaximizedPromise = windowIsMaximized();

	// Update on window resize
	window.addEventListener('resize', () => {
		isMaximizedPromise = windowIsMaximized();
	});
</script>

<div
	data-tauri-drag-region
	class="h-8 bg-primary-200 toolbar text-neutral-400 flex flex-row col-span-2
  items-center justify-between text-sm border-b border-neutral-600"
>
	<div class="flex">
		<ul class="space-x-4 flex flex-row select-none w-min ml-4">
			<li>File</li>
			<li>Edit</li>
			<li>View</li>
			<li>Help</li>
		</ul>

		<div class="bg-primary-300 rounded-lg px-3 text-md text-gray-500 ml-8">
			{$currentLocation.pathname}
		</div>
	</div>

	<div class="text-base flex h-full">
		<button class="h-full hover:bg-neutral-700 hover:text-white px-3" on:click={() => appWindow.minimize()}>
			<Icon src={VscChromeMinimize} />
		</button>

		{#await isMaximizedPromise}
			<button class="h-full hover:bg-neutral-700 hover:text-white px-3" on:click={() => appWindow.maximize()}>
				<Icon src={VscChromeMaximize} />
			</button>
		{:then response}
			{#if response}
				<button class="h-full hover:bg-neutral-700 hover:text-white px-3" on:click={() => appWindow.unmaximize()}>
					<Icon src={VscChromeRestore} />
				</button>
			{:else}
				<button class="h-full hover:bg-neutral-700 hover:text-white px-3" on:click={() => appWindow.maximize()}>
					<Icon src={VscChromeMaximize} />
				</button>
			{/if}
		{/await}

		<button class="h-full hover:bg-red-600 hover:text-white px-3" on:click={() => appWindow.close()}>
			<Icon src={VscChromeClose} />
		</button>
	</div>
</div>

// src/components/navigation/chrome.jsx
import { VscChromeClose, VscChromeRestore, VscChromeMinimize, VscChromeMaximize } from 'react-icons/vsc'
import { appWindow } from "@tauri-apps/api/window";
import useIsMaximized from "../hooks/is-maximized";
import { useLocation } from "react-router-dom";

function MinimizeButton() {
  return (
      <button className="h-full hover:bg-neutral-700 hover:text-white px-3" onClick={() => appWindow.minimize()}>
        <VscChromeMinimize />
      </button>
  )
}

function MaximizeButton() {
  const isMaximized = useIsMaximized();
  if (isMaximized === undefined) return null;
  if (isMaximized) {
    return (
        <button className="h-full hover:bg-neutral-700 hover:text-white px-3" onClick={() => appWindow.unmaximize()}>
          <VscChromeRestore />
        </button>
    )
  } else {
    return (
      <button className="h-full hover:bg-neutral-700 hover:text-white px-3" onClick={() => appWindow.maximize()}>
        <VscChromeMaximize />
      </button>
    )
  }
}

function CloseButton() {
  return (
      <button className="h-full hover:bg-red-600 hover:text-white px-3" onClick={() => appWindow.close()}>
        <VscChromeClose />
      </button>
  )
}


export default function Chrome() {
  const location = useLocation();
  return (
      <div data-tauri-drag-region className="h-8 bg-primary-200 toolbar text-neutral-400 flex flex-row col-span-2
       items-center justify-between text-sm border-b border-neutral-600">
        <div className="flex">
          <ul className="space-x-4 flex flex-row select-none w-min ml-4">
            <li>File</li>
            <li>Edit</li>
            <li>View</li>
            <li>Help</li>
          </ul>

          <div className="bg-primary-300 rounded-lg px-3 text-md text-gray-500 ml-8">{location.pathname}</div>
        </div>
        <div className="text-base flex h-full">
          <MinimizeButton />
          <MaximizeButton />
          <CloseButton />
        </div>
      </div>
  )
}
